[project]
name = "orekit-support"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.0.2",
    "jupyterlab-git>=0.51.4",
    "notebook>=7.4.3",
    "orekit-jpype>=13.1.4.0",
    "orekitdata",
]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
orekit-support = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.uv.sources]
orekitdata = { git = "https://gitlab.orekit.org/orekit/orekit-data.git" }

#[tool.uv]
#override-dependencies = [
#  "jpype1==1.5.0",
#]